# This is a basic workflow to help you get started with Actions

name: Send hint to email

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Cypress run 🧪
        #  https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/integration/wordle/test.js'
        env:
          CYPRESS_TEST_VARIABLE: ${{ secrets.MY_SECRET_VAR }}
