# This is a basic workflow to help you get started with Actions

name: Send hint to email

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  hint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Cypress run 🧪
        #  https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/integration/wordle/test.js'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          WORDLE_HINT_EMAIL: ${{ secrets.WORDLE_HINT_EMAIL }}
