name: Should provide start word

on: 
  workflow_dispatch:
    inputs:
      startWord:
        description: Pick the first word
        type: string
        default: 'start'
        required: true
jobs:
  startword:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Cypress run 🧪
        #  https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/integration/wordle/provide_start_word.spec.js'
          env: 'startWord=${{ github.event.inputs.startWord }}'
          record: true
          tag: start-word
        env:
          CYPRESS_RECORD_KEY: '${{ secrets.CYPRESS_RECORD_KEY }}'
